# -*- coding: utf-8 -*-
"""Tamil DD-DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvDVdEhkk_gyiGzVZUg65qEE6CRlz8mp
"""

# Tamil Depression Detection - DravidianLangTech ACL 2026
# Hybrid Architecture: CNN for phonetic patterns, BiLSTM for temporal contex
import os
import warnings
import numpy as np
import librosa
from tqdm import tqdm
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models

# Suppress librosa/TF warnings
warnings.filterwarnings('ignore')

# Configuration
# Change these paths to your local dataset directory
BASE_DIR = 'Tamil_Dataset'
TRAIN_DIR = os.path.join(BASE_DIR, 'train')
VAL_DIR = os.path.join(BASE_DIR, 'val')


SAMPLE_RATE = 16000
DURATION = 5
N_MFCC = 40
MAX_TIME_STEPS = 157

def extract_features(file_path):
    """Extracts stacked MFCC, Delta, and Delta-Delta features."""
    try:
        audio, sr = librosa.load(file_path, sr=SAMPLE_RATE, duration=DURATION)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=N_MFCC)
        mfcc_delta = librosa.feature.delta(mfcc)
        mfcc_delta2 = librosa.feature.delta(mfcc, order=2)

        # 3-channel stack (Phonetic 'Image')
        return np.stack([mfcc, mfcc_delta, mfcc_delta2], axis=-1)
    except Exception:
        return None

# Loading data
def load_data(directory):
    features, labels = [], []
    classes = ['Depressed', 'Non_depressed']

    for idx, label in enumerate(classes):
        path = os.path.join(directory, label)
        if not os.path.exists(path): continue
        for file in tqdm(os.listdir(path), desc=f"Loading {label}"):
            if file.endswith('.wav'):
                feat = extract_features(os.path.join(path, file))
                if feat is not None:
                    features.append(feat)
                    labels.append(idx)
    return np.array(features), np.array(labels)

# Model Architecture
def build_tamil_model(input_shape):
    model = models.Sequential([
        layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=input_shape),
        layers.MaxPooling2D((2, 2)),
        layers.BatchNormalization(),

        layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.BatchNormalization(),

        layers.Reshape((input_shape[0] // 4, -1)),

        layers.Bidirectional(layers.LSTM(64, return_sequences=False)),
        layers.Dropout(0.5),

        layers.Dense(64, activation='relu'),
        layers.Dense(2, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

#Main Exexution
#1. Load data (Assuming local structure matches your folder names)
#X_train, y_train = load_data(TRAIN_DIR)
#X_val, y_val = load_data(VAL_DIR)

# 2. Build and Train
#input_shape = (N_MFCC, MAX_TIME_STEPS, 3)
#model = build_tamil_model(input_shape)
#history = model.fit(
#    X_train,
#    y_train,
#    validation_data=(X_val, y_val),
#    epochs=30,
#    batch_size=32
#)