# -*- coding: utf-8 -*-
"""Malayalam DD-DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HgPvKN6QmIu9EKzodoE-GOn8CvcIw7vB
"""

# Malayalam Depression Detection - DravidianLangTech ACL 2026
# Hybrid Architecture: CNN for phonetic patterns, BiLSTM for temporal context
import os
import warnings
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models

# Suppress librosa/TF warnings
warnings.filterwarnings('ignore')

# Configuration
# Change these paths to your local dataset directory
BASE_DIR = 'Malayalam'
TRAIN_DIR = os.path.join(BASE_DIR, 'train')
VAL_DIR = os.path.join(BASE_DIR, 'val')


SAMPLE_RATE = 16000
DURATION = 5
N_MFCC = 40
MAX_TIME_STEPS = 157

def extract_mfcc(file_path):
    """
    Extracts MFCC, Delta, and Delta-Delta features.
    """
    try:
        audio, sr = librosa.load(file_path, sr=SAMPLE_RATE, duration=DURATION)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=N_MFCC)

        # Add Delta and Delta-Delta features
        mfcc_delta = librosa.feature.delta(mfcc)
        mfcc_delta2 = librosa.feature.delta(mfcc, order=2)

        # Combine into a 3-channel feature set
        combined = np.stack([mfcc, mfcc_delta, mfcc_delta2], axis=-1)
        return combined
    except Exception as e:
        return None

# Loading data
def load_dataset(directory):
    features = []
    labels = []
    classes = ['Depression', 'Non-depression']

    for label_idx, label_name in enumerate(classes):
        folder_path = os.path.join(directory, label_name)
        if not os.path.exists(folder_path): continue

        for file_name in tqdm(os.listdir(folder_path), desc=f"Loading {label_name}"):
            if file_name.endswith('.wav'):
                feat = extract_mfcc(os.path.join(folder_path, file_name))
                if feat is not None:
                    features.append(feat)
                    labels.append(label_idx)
    return np.array(features), np.array(labels)

# Model Architechture
def build_model(input_shape):
    model = models.Sequential([
        # CNN Block
        layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=input_shape),
        layers.MaxPooling2D((2, 2)),
        layers.BatchNormalization(),

        layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.BatchNormalization(),

        # Reshape for BiLSTM input: (Time_steps, Features)
        layers.Reshape((input_shape[0] // 4, -1)),

        # Recurrent Block
        layers.Bidirectional(layers.LSTM(64, return_sequences=False)),
        layers.Dropout(0.5),

        # Dense Block
        layers.Dense(64, activation='relu'),
        layers.Dense(2, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

# Main Execution
# 1. Load data (Assuming local structure matches your folder names)
# X_train, y_train = load_dataset(TRAIN_DIR)
# X_val, y_val = load_dataset(VAL_DIR)

# 2. Build and Train
# input_shape = (N_MFCC, MAX_TIME_STEPS, 3)
# model = build_model(input_shape)
# history = model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=30, batch_size=32)